# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358a49df11c9d48a8053cb337cc94cd2e1f337a379e7aced9b6697cefbdbe39b159e25a25c983da9db0fd0342681024d93e990c4d0ac04b68002209b53a8405c

test:
  secret_key_base: c873ba9f8e21abbe81671dff40bba703973a398e2106dbda6ca57cf224b1c4a1559948c7ea706cb323ae16e447758999eb4445316d48d13c15327099cc7c8e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
